/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RailgunSimulator.GUI;


import RailgunSimulator.controller.CriarSegmentoController;
import RailgunSimulator.controller.SimularRailgunController;
import RailgunSimulator.model.*;
import java.io.FileNotFoundException;


/**
 *
 * @author Bruno Freitas
 */
public class CriarSegmentoUI extends javax.swing.JDialog {

    private final Railgun railGun;
   

    private final CriarSegmentoController csc;

    private final SimularRailgunController src;
    private final double massa;

    /**
     * Creates new form CriarSegmentoSemMassa
     *
     * @param parent
     * @param modal
     * @param r
     * @param massa
     */
    public CriarSegmentoUI(java.awt.Frame parent, boolean modal, Railgun r, double massa) {
        super(parent, modal);
        this.railGun = r;
        initComponents();
        setLocationRelativeTo(null);
        csc = new CriarSegmentoController(this.railGun);
        src = new SimularRailgunController(this.railGun);
        this.massa = massa;
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        limpar_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        intensidade_textfield = new javax.swing.JTextField();
        raio_textfield = new javax.swing.JTextField();
        comprimento_textfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        guardar_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        seg_table = new javax.swing.JTable();
        simular_railgun_button = new javax.swing.JButton();
        apagar_seg_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        limpar_button.setText("Limpar campos");
        limpar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_buttonActionPerformed(evt);
            }
        });

        jLabel3.setText("Comprimento dos trilhos (m)");

        intensidade_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intensidade_textfieldActionPerformed(evt);
            }
        });

        raio_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raio_textfieldActionPerformed(evt);
            }
        });

        comprimento_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprimento_textfieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Intensidade do campo elétrico (N/C)");

        guardar_button.setText("Guardar");
        guardar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_buttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Raio dos trilhos (m)");

        seg_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Segmento", "Intensidade campo eletrico", "Raio dos trilhos", "Comprimento dos trilhos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        seg_table.setColumnSelectionAllowed(true);
        seg_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(seg_table);
        seg_table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        simular_railgun_button.setText("Simular");
        simular_railgun_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simular_railgun_buttonActionPerformed(evt);
            }
        });

        apagar_seg_button.setText("Apagar");
        apagar_seg_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagar_seg_buttonActionPerformed(evt);
            }
        });

        jButton1.setText("Criar Ficheiro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(guardar_button)
                        .addGap(18, 18, 18)
                        .addComponent(limpar_button)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(intensidade_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comprimento_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(raio_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(simular_railgun_button)
                .addGap(40, 40, 40)
                .addComponent(apagar_seg_button)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intensidade_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(raio_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comprimento_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(simular_railgun_button)
                        .addComponent(apagar_seg_button)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(guardar_button)
                        .addComponent(limpar_button)))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_buttonActionPerformed
        intensidade_textfield.setText("");
        raio_textfield.setText("");
        comprimento_textfield.setText("");
    }//GEN-LAST:event_limpar_buttonActionPerformed

    private void intensidade_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intensidade_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intensidade_textfieldActionPerformed

    private void raio_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raio_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raio_textfieldActionPerformed

    private void comprimento_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprimento_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comprimento_textfieldActionPerformed

    private void guardar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_buttonActionPerformed
        double intensidade = Double.parseDouble(intensidade_textfield.getText());
        double raio = Double.parseDouble(raio_textfield.getText());
        double comprimento = Double.parseDouble(comprimento_textfield.getText());
        if (intensidade != 0 && raio != 0 && comprimento != 0) {
            Segmento seg = new Segmento(intensidade, raio, comprimento);
            int linha = this.railGun.getSize();
            seg_table.setValueAt(linha + 1, linha, 0);
            seg_table.setValueAt(intensidade, linha, 1);
            seg_table.setValueAt(raio, linha, 2);
            seg_table.setValueAt(comprimento, linha, 3);
            this.csc.inserirSegmento(seg);
        }

    }//GEN-LAST:event_guardar_buttonActionPerformed

    private void apagar_seg_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagar_seg_buttonActionPerformed
        int index_a_apagar = seg_table.getSelectedRow();
        seg_table.remove(index_a_apagar);
    }//GEN-LAST:event_apagar_seg_buttonActionPerformed

    private void simular_railgun_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simular_railgun_buttonActionPerformed
        SimularRailgunUI srui = new SimularRailgunUI(null, true, this.railGun,this.massa);
        srui.setVisible(true);
    }//GEN-LAST:event_simular_railgun_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       FicheiroUI fui = new FicheiroUI();
       fui.setVisible(true);
       
        
       HTMLFile f = new HTMLFile();
       try{
       f.novoFicheiro(src);
       }catch (FileNotFoundException e){
           
       }
       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apagar_seg_button;
    private javax.swing.JTextField comprimento_textfield;
    private javax.swing.JButton guardar_button;
    private javax.swing.JTextField intensidade_textfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpar_button;
    private javax.swing.JTextField raio_textfield;
    private javax.swing.JTable seg_table;
    private javax.swing.JButton simular_railgun_button;
    // End of variables declaration//GEN-END:variables
}
