/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RailgunSimulator.GUI;

import RailgunSimulator.controller.CriarSegmentoController;
import RailgunSimulator.model.Calculos;
import RailgunSimulator.model.Railgun;
import RailgunSimulator.model.Segmento;

/**
 *
 * @author Bruno Freitas
 */
public class CriarSegmentoUI extends javax.swing.JDialog {

    private final Railgun railGun;
    
    private final CriarSegmentoController csc;

    /**
     * Creates new form ConstruirSegmento
     */
    public CriarSegmentoUI(java.awt.Frame parent, boolean modal, Railgun r) {
        super(parent, modal);
        this.railGun = r;
        initComponents();
        setLocationRelativeTo(null);
        csc = new CriarSegmentoController(this.railGun);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        raio_textfield = new javax.swing.JTextField();
        massa_textfield = new javax.swing.JTextField();
        comprimento_textfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        guardar_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        limpar_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        intensidade_textfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar Segmento");

        raio_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raio_textfieldActionPerformed(evt);
            }
        });

        massa_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                massa_textfieldActionPerformed(evt);
            }
        });

        comprimento_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprimento_textfieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Intensidade do campo elétrico (N/C)");

        guardar_button.setText("Guardar");
        guardar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_buttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Raio dos trilhos (m)");

        limpar_button.setText("Limpar campos");

        jLabel3.setText("Comprimento dos trilhos (m)");

        jLabel4.setText("Massa do projétil (Kg)");

        intensidade_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intensidade_textfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guardar_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(limpar_button))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(intensidade_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(massa_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comprimento_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(raio_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(55, 55, 55))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comprimento_textfield, intensidade_textfield, massa_textfield, raio_textfield});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intensidade_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(raio_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comprimento_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(massa_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar_button)
                    .addComponent(limpar_button))
                .addGap(42, 42, 42))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comprimento_textfield, intensidade_textfield, massa_textfield, raio_textfield});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void raio_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raio_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raio_textfieldActionPerformed

    private void massa_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_massa_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_massa_textfieldActionPerformed

    private void comprimento_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprimento_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comprimento_textfieldActionPerformed

    private void intensidade_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intensidade_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intensidade_textfieldActionPerformed

    private void guardar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_buttonActionPerformed
        double intensidade = Double.parseDouble(intensidade_textfield.getText());
        double raio = Double.parseDouble(raio_textfield.getText());
        double comprimento = Double.parseDouble(comprimento_textfield.getText());
        double massa = Double.parseDouble(massa_textfield.getText());
        Segmento seg = new Segmento(intensidade, massa, raio, comprimento);
        csc.setS(seg);
        this.csc.run();
        dispose();
    }//GEN-LAST:event_guardar_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField comprimento_textfield;
    private javax.swing.JButton guardar_button;
    private javax.swing.JTextField intensidade_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton limpar_button;
    private javax.swing.JTextField massa_textfield;
    private javax.swing.JTextField raio_textfield;
    // End of variables declaration//GEN-END:variables
}
