/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RailgunSimulator.GUI;

import RailgunSimulator.controller.SimularRailgunController;
import RailgunSimulator.model.Railgun;

/**
 *
 * @author Bruno Freitas
 */
public class SimularRailgunUI extends javax.swing.JDialog {

    private final Railgun railGun;

    private final SimularRailgunController src;

    /**
     * Creates new form SimularRailgunUI
     */
    public SimularRailgunUI(java.awt.Frame parent, boolean modal, Railgun r) {
        super(parent, modal);
        this.railGun = r;
        initComponents();
        setLocationRelativeTo(null);
        src = new SimularRailgunController(this.railGun);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        num_seg_textfield = new javax.swing.JTextField();
        forca_textfield = new javax.swing.JTextField();
        aceleracao_textfield = new javax.swing.JTextField();
        velocidade_textfield = new javax.swing.JTextField();
        simular_button = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Simulador de railgun");
        setPreferredSize(new java.awt.Dimension(400, 250));
        setResizable(false);

        jLabel2.setText("Número de segmentos");

        jLabel3.setText("Forca (N/m)");

        jLabel4.setText("Aceleração do projétil (m/s^2)");

        jLabel5.setText("Velocidade final do projétil (m/s)");

        num_seg_textfield.setEditable(false);
        num_seg_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_seg_textfieldActionPerformed(evt);
            }
        });

        forca_textfield.setEditable(false);
        forca_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forca_textfieldActionPerformed(evt);
            }
        });

        aceleracao_textfield.setEditable(false);

        velocidade_textfield.setEditable(false);

        simular_button.setText("Simular");
        simular_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simular_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(simular_button)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(forca_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(aceleracao_textfield, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(velocidade_textfield, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num_seg_textfield))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(num_seg_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(forca_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceleracao_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(velocidade_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(simular_button)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num_seg_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_seg_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_seg_textfieldActionPerformed

    private void forca_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forca_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forca_textfieldActionPerformed

    private void simular_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simular_buttonActionPerformed
      String arr[] = this.src.getInfo();
      this.num_seg_textfield.setText(arr[0]);
      this.forca_textfield.setText(arr[1]);
      this.aceleracao_textfield.setText(arr[2]);
      this.velocidade_textfield.setText(arr[3]);
    }//GEN-LAST:event_simular_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aceleracao_textfield;
    private javax.swing.JTextField forca_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField num_seg_textfield;
    private javax.swing.JButton simular_button;
    private javax.swing.JTextField velocidade_textfield;
    // End of variables declaration//GEN-END:variables
}
